import type { Game, GameFormState } from "../../../backlog/shared";

export const defaultGames: Game[] = [
  {
    id: 1,
    title: "Cyberpunk 2077",
    platform: "PC",
    genre: "RPG",
    status: "Jogando",
    progress: 65,
    hours: 42,
    eta: "25h",
    priority: "Alta",
    mood: "Energia",
    score: 9.0,
    year: 2020,
    notes: "Imersao total no Night City, foco em Side Quests.",
    difficulty: "Média",
  },
  {
    id: 2,
    title: "Elden Ring",
    platform: "PS5",
    genre: "Soulslike",
    status: "Pausado",
    progress: 30,
    hours: 25,
    eta: "60h",
    priority: "Média",
    mood: "Foco",
    score: 9.5,
    year: 2022,
    notes: "Explorando Liurnia, grind necessario.",
    difficulty: "Alta",
  },
  {
    id: 3,
    title: "Balatro",
    platform: "Switch",
    genre: "Roguelike",
    status: "Backlog",
    progress: 0,
    hours: 0,
    eta: "Infinito",
    priority: "Alta",
    mood: "Cozy",
    score: 10,
    year: 2024,
    notes: "Apenas mais uma run...",
    difficulty: "Média",
  },
];

export const defaultGameForm: GameFormState = {
  title: "",
  platform: "PC",
  genre: "",
  status: "Backlog",
  priority: "Média",
  progress: "0",
  hours: "0",
  eta: "12h",
  score: "",
  year: String(new Date().getFullYear()),
  mood: "",
  difficulty: "Média",
  notes: "",
};
